invoice/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'digital_invoices#index'
  
  resources :digital_invoices,  only: [:index] do
  	post :upload, on: :collection 
  	post :download, on: :member
  end
end

invoice/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

invoice/app/models/digital_invoice.rb
class DigitalInvoice < ApplicationRecord
	require 'carrierwave/orm/activerecord'
	mount_uploader :raw, InvoiceUploader
	mount_uploader :processed, InvoiceUploader

end

invoice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

invoice/app/controllers/digital_invoice_controller.rb
#class UploadController < ApplicationController
class DigitalInvoiceController < ApplicationController

require 'carrierwave/orm/activerecord'
   

	def upload
    di = DigitalInvoice.new
    di.raw = params[:upload]
    di.save!  
    #send the uploaded file to parse method
    Parser.parse(di)
    flash[:notice] = "File successfully processed"
    redirect_to root_path
   
  end

  def download
      file_id = params[:file] 
      type =  params[:type] == "processed"  ? "processed" : "raw"
      file_path = DigitalInvoice.find(file_id).send(type).current_path
      send_file(file_path,
      type: 'application/text',
      disposition: 'attachment'
       )
  end

end

invoice/app/controllers/digital_invoices_controller.rb
class DigitalInvoicesController < ApplicationController

require 'carrierwave/orm/activerecord'
   
  def index
    @digital_invoices = DigitalInvoice.all
    @digital_invoice = DigitalInvoice.new
  end

	def upload
    di = DigitalInvoice.create(digital_invoices_params)
    #send the uploaded file to parse method
    #skipping validation on the inout file
    Parser.parse(di)
    flash[:notice] = "File successfully processed"
    redirect_to root_path
   
  end

  def download
      file_id = params[:id] 
      type =  params[:type] == "processed"  ? "processed" : "raw"
      file_path = DigitalInvoice.find(file_id).send(type).current_path
      send_file(file_path,
      type: 'application/text',
      disposition: 'attachment'
       )
  end

  protected

  def digital_invoices_params
    params.require(:digital_invoice).permit(:raw)
  end

end

invoice/app/helpers/application_helper.rb
module ApplicationHelper
end

invoice/app/helpers/upload_helper.rb
module UploadHelper
end

invoice/app/views/digital_invoices/index.html.erb
<div class="alert alert-success">
  <strong><%= flash[:notice] %></strong>
</div>

<div class="container" align="center" >
    <div class="page-header" ><p class="text-info">UPLOAD 7 SEGMENTED INVOICES FILE</p></div>

    	<%= form_for @digital_invoice , url: upload_digital_invoices_path, multipart: true do |f| %>
        	<%= f.file_field :raw , class: 'btn-default' %></p>
        	<%= f.submit "UPLOAD" , class: 'btn btn-success' %>
    	<% end %>    
    </div>
</br>

<div class="container intpol3">
    <% unless @digital_invoices.blank? %> 
        <table class="table table-bordered">    
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Original File</th>
                    <th>Processed File</th>
                  </tr>
                </thead>
                <% @digital_invoices.each_with_index do |di, i| %>
                    <tr>
                        <td><%= i+1 %></td>
                        <td><%= link_to "Download #{di.raw_identifier}", download_digital_invoice_path(id: di, type: "raw"), method: :post %></td>
                        <td><%= link_to "Download #{di.processed_identifier}", download_digital_invoice_path(id: di , type: "processed"), method: :post  %></td>
                    </tr>            
                <% end %>       
        </table>
    <% end %>
</div>

invoice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invoice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>